# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            EmilRex
tagline:          'A blog about data'
description:      'A blog about data'
url:              https://emilrex.com
baseurl:          /

author:
  name:           'Emil Christensen'
  url:            https://github.com/EmilRex

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/EmilRex/EmilRex
