# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            EmilRex
tagline:          'Thoughts on data'
description:      'Thoughts on data'
url:              https://emilrex.com
baseurl:          /

author:
  name:           'Emil Christensen'
  url:            https://github.com/EmilRex

paginate:         5
